//! File-based storage. No SQLite, no database: notes are plain `.txt` files,
//! state lives in small JSON sidecars, and everything is inspectable by the user.
//!
//! Layout (documented in PLAN.md — this *is* the database):
//! ```text
//! <root>/notes/<id>.txt      one file per note
//! <root>/trash/<id>.txt      deleted notes, purged after 30 days
//! <root>/state/*.json        settings, index, geometry, timers, trash meta
//! ```

use crate::{new_note_id, now_ms, title_from_text, Note, NoteMeta, TrashEntry};
use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

const TRASH_RETENTION_MS: u64 = 30 * 24 * 60 * 60 * 1000;

#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, Default)]
struct IndexEntry {
    pinned: bool,
    plain: bool,
}

#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, Default)]
struct IndexDoc {
    order: Vec<String>,
    entries: BTreeMap<String, IndexEntry>,
}

/// File-backed note store. All mutations are atomic (write temp, then rename),
/// so a crash or power loss cannot corrupt a note (PRD reliability requirement).
pub struct FileStore {
    root: PathBuf,
    index: IndexDoc,
}

fn write_atomic(path: &Path, bytes: &[u8]) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let tmp = path.with_extension(format!("tmp{}", std::process::id()));
    {
        let mut f = fs::File::create(&tmp)?;
        f.write_all(bytes)?;
        f.sync_all().ok(); // best effort durability
    }
    fs::rename(&tmp, path)
}

fn read_json_or<T: serde::de::DeserializeOwned + Default>(path: &Path) -> T {
    fs::read(path)
        .ok()
        .and_then(|b| serde_json::from_slice(&b).ok())
        .unwrap_or_default()
}

fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for &b in bytes {
        h ^= b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

/// Content hash used by sync and integrity checks (stable across devices).
pub fn content_hash(bytes: &[u8]) -> u64 {
    fnv1a64(bytes)
}

impl FileStore {
    /// Open (or initialise) the store rooted at `root`. Creates the folder tree
    /// and rebuilds any missing index from the note files themselves.
    pub fn open(root: &Path) -> std::io::Result<Self> {
        fs::create_dir_all(root.join("notes"))?;
        fs::create_dir_all(root.join("trash"))?;
        fs::create_dir_all(root.join("state"))?;
        let mut store = Self { root: root.to_path_buf(), index: IndexDoc::default() };
        store.index = read_json_or(&store.root.join("state/index.json"));
        store.rebuild_index_if_needed()?;
        store.purge_expired_trash()?;
        Ok(store)
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    // ---------- index ----------

    fn rebuild_index_if_needed(&mut self) -> std::io::Result<()> {
        let mut on_disk: Vec<String> = Vec::new();
        for entry in fs::read_dir(self.root.join("notes"))? {
            let p = entry?.path();
            if p.extension().is_some_and(|e| e == "txt") {
                if let Some(stem) = p.file_stem().and_then(|s| s.to_str()) {
                    on_disk.push(stem.to_string());
                }
            }
        }
        on_disk.sort();
        let known: Vec<String> =
            self.index.order.iter().filter(|id| on_disk.contains(id)).cloned().collect();
        let new_ids: Vec<String> =
            on_disk.iter().filter(|id| !self.index.order.contains(id)).cloned().collect();
        let mut order = known;
        order.extend(new_ids);
        // Newest first for newly discovered notes: keep index order otherwise.
        self.index.order = order;
        self.save_index()
    }

    fn save_index(&self) -> std::io::Result<()> {
        write_atomic(
            &self.root.join("state/index.json"),
            &serde_json::to_vec_pretty(&self.index).unwrap_or_default(),
        )
    }

    // ---------- notes ----------

    /// Every note, newest-modified first (pinned notes always lead).
    pub fn list_notes(&self) -> Vec<NoteMeta> {
        let mut metas: Vec<NoteMeta> = self.index.order.iter().filter_map(|id| self.load_meta(id)).collect();
        metas.sort_by(|a, b| b.pinned.cmp(&a.pinned).then(b.mtime_ms.cmp(&a.mtime_ms)));
        metas
    }

    fn note_path(&self, id: &str, trash: bool) -> PathBuf {
        let sub = if trash { "trash" } else { "notes" };
        // id is generated by us and used as a filename; reject anything odd.
        let safe = id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-');
        if !safe {
            return self.root.join(sub).join("rejected.txt");
        }
        self.root.join(sub).join(format!("{id}.txt"))
    }

    fn load_meta(&self, id: &str) -> Option<NoteMeta> {
        let text = self.load_text(id, false)?;
        let mtime = fs::metadata(self.note_path(id, false))
            .and_then(|m| m.modified())
            .ok()
            .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
            .map(|d| d.as_millis() as u64)
            .unwrap_or(0);
        let entry = self.index.entries.get(id).cloned().unwrap_or_default();
        Some(NoteMeta {
            id: id.to_string(),
            title: title_from_text(&text),
            mtime_ms: mtime,
            pinned: entry.pinned,
            plain: entry.plain,
        })
    }

    fn load_text(&self, id: &str, trash: bool) -> Option<String> {
        fs::read_to_string(self.note_path(id, trash)).ok()
    }

    /// Load a note (metadata + text).
    pub fn load_note(&self, id: &str) -> Option<Note> {
        let meta = self.load_meta(id)?;
        let text = self.load_text(id, false)?;
        Some(Note { meta, text })
    }

    /// Save a note: writes the file, updates the index, returns fresh metadata.
    /// Empty notes are not persisted (PRD N-3): the caller decides to discard.
    pub fn save_note(&mut self, id: &str, text: &str) -> std::io::Result<NoteMeta> {
        let bytes = text.as_bytes();
        let changed = match fs::read(self.note_path(id, false)) {
            Ok(old) => content_hash(&old) != content_hash(bytes),
            Err(_) => true,
        };
        if changed {
            write_atomic(&self.note_path(id, false), bytes)?;
        }
        if !self.index.order.contains(&id.to_string()) {
            self.index.order.insert(0, id.to_string());
        }
        self.index.entries.entry(id.to_string()).or_default();
        self.save_index()?;
        self.load_meta(id).ok_or_else(|| std::io::Error::other("meta missing after save"))
    }

    /// Create a new empty note id without touching disk (persisted on first save).
    pub fn create_note(&self) -> String {
        new_note_id(now_ms())
    }

    /// Move a note to trash (recoverable for 30 days).
    pub fn delete_note(&mut self, id: &str) -> std::io::Result<()> {
        let src = self.note_path(id, false);
        if src.exists() {
            let dst = self.note_path(id, true);
            write_atomic(&dst, &fs::read(&src)?)?;
            fs::remove_file(&src)?;
        }
        let mut trash: Vec<TrashEntry> = read_json_or(&self.root.join("state/trash.json"));
        let title = self.load_text(id, true).map(|t| title_from_text(&t)).unwrap_or_default();
        trash.retain(|e| e.id != id);
        trash.push(TrashEntry { id: id.to_string(), title, deleted_at_ms: now_ms() });
        write_atomic(&self.root.join("state/trash.json"), &serde_json::to_vec(&trash)?)?;
        self.index.order.retain(|x| x != id);
        self.index.entries.remove(id);
        self.save_index()
    }

    /// Restore a trashed note to the live stack.
    pub fn restore_note(&mut self, id: &str) -> std::io::Result<Option<String>> {
        let src = self.note_path(id, true);
        if !src.exists() {
            return Ok(None);
        }
        write_atomic(&self.note_path(id, false), &fs::read(&src)?)?;
        fs::remove_file(&src)?;
        let mut trash: Vec<TrashEntry> = read_json_or(&self.root.join("state/trash.json"));
        trash.retain(|e| e.id != id);
        write_atomic(&self.root.join("state/trash.json"), &serde_json::to_vec(&trash)?)?;
        if !self.index.order.contains(&id.to_string()) {
            self.index.order.insert(0, id.to_string());
        }
        self.save_index()?;
        Ok(Some(id.to_string()))
    }

    pub fn list_trash(&self) -> Vec<TrashEntry> {
        let mut t: Vec<TrashEntry> = read_json_or(&self.root.join("state/trash.json"));
        t.sort_by_key(|b| std::cmp::Reverse(b.deleted_at_ms));
        t
    }

    fn purge_expired_trash(&mut self) -> std::io::Result<()> {
        let now = now_ms();
        let trash: Vec<TrashEntry> = read_json_or(&self.root.join("state/trash.json"));
        let keep: Vec<TrashEntry> = trash
            .into_iter()
            .filter(|e| {
                if now.saturating_sub(e.deleted_at_ms) > TRASH_RETENTION_MS {
                    fs::remove_file(self.note_path(&e.id, true)).ok();
                    false
                } else {
                    true
                }
            })
            .collect();
        write_atomic(&self.root.join("state/trash.json"), &serde_json::to_vec(&keep)?)
    }

    // ---------- per-note flags ----------

    pub fn set_pinned(&mut self, id: &str, pinned: bool) -> std::io::Result<()> {
        self.index.entries.entry(id.to_string()).or_default().pinned = pinned;
        self.save_index()
    }

    pub fn set_plain(&mut self, id: &str, plain: bool) -> std::io::Result<()> {
        self.index.entries.entry(id.to_string()).or_default().plain = plain;
        self.save_index()
    }

    // ---------- settings / geometry (JSON sidecars) ----------

    pub fn get_settings(&self) -> serde_json::Value {
        read_json_or(&self.root.join("state/settings.json"))
    }

    pub fn set_setting(&mut self, key: &str, value: serde_json::Value) -> std::io::Result<()> {
        let mut doc = self.get_settings();
        if !doc.is_object() {
            doc = serde_json::json!({}); // first write: file absent or null
        }
        if let Some(obj) = doc.as_object_mut() {
            obj.insert(key.to_string(), value);
        }
        write_atomic(&self.root.join("state/settings.json"), &serde_json::to_vec_pretty(&doc)?)
    }

    pub fn get_geometry(&self) -> serde_json::Value {
        read_json_or(&self.root.join("state/geometry.json"))
    }

    pub fn set_geometry(&mut self, geo: serde_json::Value) -> std::io::Result<()> {
        write_atomic(&self.root.join("state/geometry.json"), &serde_json::to_vec(&geo)?)
    }

    /// All note names with content hashes — the sync manifest.
    pub fn manifest(&self) -> BTreeMap<String, (u64, u64)> {
        let mut m = BTreeMap::new();
        for id in &self.index.order {
            if let Ok(bytes) = fs::read(self.note_path(id, false)) {
                let mtime = fs::metadata(self.note_path(id, false))
                    .and_then(|md| md.modified())
                    .ok()
                    .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
                    .map(|d| d.as_millis() as u64)
                    .unwrap_or(0);
                m.insert(id.clone(), (content_hash(&bytes), mtime));
            }
        }
        m
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmpdir(tag: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!("plainpad-test-{tag}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&d);
        d
    }

    #[test]
    fn save_load_list_delete_restore_roundtrip() {
        let dir = tmpdir("roundtrip");
        let mut s = FileStore::open(&dir).unwrap();

        let id = s.create_note();
        let meta = s.save_note(&id, "hello world\nsecond line").unwrap();
        assert_eq!(meta.title, "hello world");

        let note = s.load_note(&id).unwrap();
        assert_eq!(note.text, "hello world\nsecond line");

        // list shows it newest-first
        let list = s.list_notes();
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].id, id);

        // delete → trash → restore
        s.delete_note(&id).unwrap();
        assert!(s.load_note(&id).is_none());
        assert_eq!(s.list_trash().len(), 1);
        assert!(s.restore_note(&id).unwrap().is_some());
        assert_eq!(s.load_note(&id).unwrap().text, "hello world\nsecond line");
        assert!(s.list_trash().is_empty());
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn index_is_rebuilt_from_files_after_loss() {
        let dir = tmpdir("rebuild");
        let mut s = FileStore::open(&dir).unwrap();
        let id = s.create_note();
        s.save_note(&id, "survivor").unwrap();

        // Simulate index corruption/loss: delete the file, reopen the store.
        fs::remove_file(dir.join("state/index.json")).unwrap();
        let s2 = FileStore::open(&dir).unwrap();
        let list = s2.list_notes();
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].id, id);
        assert_eq!(list[0].title, "survivor");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn empty_note_is_not_persisted() {
        let dir = tmpdir("empty");
        let mut s = FileStore::open(&dir).unwrap();
        let id = s.create_note();
        s.save_note(&id, "").unwrap();
        // File may exist (UI discards on close), but a fresh store must not list empties.
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn settings_and_flags_roundtrip() {
        let dir = tmpdir("settings");
        let mut s = FileStore::open(&dir).unwrap();
        let id = s.create_note();
        s.save_note(&id, "note").unwrap();
        s.set_setting("hotkey", serde_json::json!("Alt+A")).unwrap();
        s.set_pinned(&id, true).unwrap();
        s.set_plain(&id, true).unwrap();

        let s2 = FileStore::open(&dir).unwrap();
        assert_eq!(s2.get_settings()["hotkey"], "Alt+A");
        let m = &s2.list_notes()[0];
        assert!(m.pinned && m.plain);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn manifest_hashes_are_stable_and_sensitive() {
        let dir = tmpdir("manifest");
        let mut s = FileStore::open(&dir).unwrap();
        let id = s.create_note();
        s.save_note(&id, "abc").unwrap();
        let m1 = s.manifest();
        s.save_note(&id, "abd").unwrap();
        let m2 = s.manifest();
        let (h1, _) = m1[&id];
        let (h2, _) = m2[&id];
        assert_ne!(h1, h2);
        assert_eq!(content_hash(b"abc"), content_hash(b"abc"));
    }
}
